import type { Meta, StoryObj } from "@storybook/react"
import React from "react"
import { GlassMarkdownViewer } from "../components/glass-markdown-viewer"
import { GlassNotificationBell, GlassNotificationPanel } from "../components/glass-notification"

const meta: Meta = {
  title: "Glass Display/MarkdownNotification",
  parameters: { layout: "padded" },
}

export default meta
type Story = StoryObj

const MARKDOWN_CONTENT = `# Q4 2024 Performance Summary

**Revenue:** €231,000 (+8% vs Q3)
**Profit margin:** 34.2% (+2.1pp)

## Highlights

- Completed **14 renovation projects** ahead of schedule
- Hired **6 new field operators** for the winter expansion
- Store #4 reached \`€42,000\` monthly revenue for the first time

## Risks

> ⚠️ Project #142 is delayed by 3 days due to material supply issues.

\`\`\`
Estimated resolution: Nov 15, 2024
\`\`\`

---

*Report generated by PRV AI · October 2024*`

export const MarkdownViewer: Story = {
  name: "Markdown Viewer",
  render: () => (
    <div style={{ maxWidth: 560 }}>
      <GlassMarkdownViewer content={MARKDOWN_CONTENT} />
    </div>
  ),
}

const NOTIFICATIONS = [
  {
    id: "1",
    type: "error" as const,
    title: "Store #4 inventory critical",
    description: "Tiles below reorder threshold. Order required.",
    timestamp: "2 min ago",
  },
  {
    id: "2",
    type: "warning" as const,
    title: "Shift uncovered tomorrow",
    description: "Livia Marin on leave · Field Ops 08:00–16:00",
    timestamp: "15 min ago",
  },
  {
    id: "3",
    type: "success" as const,
    title: "Project #138 completed",
    description: "Bathroom Remodel · Ion Popescu signed off",
    timestamp: "1 hr ago",
    read: true,
  },
  {
    id: "4",
    type: "info" as const,
    title: "Payroll processed",
    description: "42 employees · October 2024",
    timestamp: "3 hr ago",
    read: true,
  },
]

export const NotificationPanel: Story = {
  name: "Notification Panel",
  render: () => (
    <div style={{ maxWidth: 380 }}>
      <GlassNotificationPanel
        entries={NOTIFICATIONS}
        onMarkAllRead={() => console.log("mark all read")}
        onDismiss={(id) => console.log("dismiss:", id)}
        onSelect={(id) => console.log("select:", id)}
        onViewAll={() => console.log("view all")}
      />
    </div>
  ),
}

export const NotificationBell: Story = {
  name: "Notification Bell",
  render: () => (
    <GlassNotificationBell
      entries={NOTIFICATIONS.filter((n) => !n.read)}
      onMarkAllRead={() => console.log("mark all read")}
      onDismiss={(id) => console.log("dismiss:", id)}
      onSelect={(id) => console.log("select:", id)}
    />
  ),
}
