export { baseTemplate, emailStyles } from "./base"
export { welcomeEmail } from "./welcome"
export type { WelcomeEmailProps } from "./welcome"
export { mfaCodeEmail } from "./mfa"
export type { MfaCodeEmailProps } from "./mfa"
export { teamInviteEmail } from "./invite"
export type { TeamInviteEmailProps } from "./invite"
export { passwordResetEmail } from "./password-reset"
export type { PasswordResetEmailProps } from "./password-reset"
export { notificationEmail } from "./notification"
export type { NotificationEmailProps } from "./notification"
export { portalMagicLinkEmail } from "./portal-magic-link"
export type { PortalMagicLinkEmailProps } from "./portal-magic-link"
export { leaveDecisionEmail } from "./leave-decision"
export type { LeaveDecisionEmailProps, LeaveDecision, LeaveType } from "./leave-decision"
export { learningCertificateEmail } from "./learning-certificate"
export type { LearningCertificateEmailProps } from "./learning-certificate"
