import type { CommandEntry } from "./types"

const CEO_ROLES = new Set(["ROLE_SUPERADMIN", "ROLE_COMPANY_OWNER", "ROLE_CEO"])

const MANAGER_ROLES = new Set([...CEO_ROLES, "ROLE_REGIONAL_MANAGER", "ROLE_STORE_MANAGER"])

const FINANCE_ROLES = new Set([...CEO_ROLES, "ROLE_FINANCE_MANAGER", "ROLE_ACCOUNTANT"])

const BASE: CommandEntry[] = [
  {
    id: "nav.dashboard",
    label: "Go to Dashboard",
    section: "Navigation",
    shortcut: "⌘1",
    keywords: ["home", "command", "kpis"],
    href: "/dashboard",
  },
  {
    id: "nav.notifications",
    label: "Notifications",
    section: "Navigation",
    shortcut: "⌘N",
    keywords: ["alerts", "inbox"],
    href: "/notifications",
  },
  {
    id: "nav.calendar",
    label: "Calendar",
    section: "Navigation",
    keywords: ["calendar", "schedule", "events", "agenda", "deadlines", "milestones"],
    href: "/calendar",
  },
  {
    id: "nav.projects",
    label: "Projects",
    section: "Navigation",
    keywords: ["renovation", "work"],
    href: "/projects",
  },
  {
    id: "nav.resources",
    label: "Resource Workload",
    section: "Navigation",
    keywords: [
      "resources",
      "workload",
      "allocation",
      "utilization",
      "capacity",
      "staffing",
      "team load",
      "over-allocated",
    ],
    href: "/projects/resources",
  },
  {
    id: "nav.people",
    label: "People & HR",
    section: "Navigation",
    keywords: ["employees", "team", "hr"],
    href: "/people",
  },
  {
    id: "nav.equipment",
    label: "Equipment Assignments",
    section: "Navigation",
    keywords: ["equipment", "asset", "gear", "tools", "assignment", "serial", "checkout", "return"],
    href: "/people/equipment",
  },
  {
    id: "nav.performance",
    label: "Team Performance",
    section: "Navigation",
    keywords: [
      "performance",
      "kpi",
      "metrics",
      "attendance rate",
      "punctuality",
      "rating",
      "heatmap",
      "review",
    ],
    href: "/people/performance",
  },
  {
    id: "nav.holidays",
    label: "Public Holidays",
    section: "Navigation",
    keywords: ["holidays", "public holiday", "calendar", "bank holiday", "non-working", "days off"],
    href: "/people/holidays",
  },
  {
    id: "nav.contracts",
    label: "Employment Contracts",
    section: "Navigation",
    keywords: [
      "contract",
      "employment",
      "hr",
      "salary",
      "hire",
      "fixed-term",
      "expiry",
      "renewal",
      "terminate",
    ],
    href: "/people/contracts",
  },
  {
    id: "nav.compliance",
    label: "HR Compliance",
    section: "Navigation",
    keywords: [
      "compliance",
      "documents",
      "passport",
      "visa",
      "certification",
      "right to work",
      "expiry",
      "verify",
    ],
    href: "/people/compliance",
  },
  {
    id: "nav.document-retention",
    label: "Document Retention",
    section: "Navigation",
    keywords: [
      "retention",
      "documents",
      "expiry",
      "archive",
      "legal hold",
      "gdpr",
      "records",
      "vault",
    ],
    href: "/documents/retention",
  },
  {
    id: "nav.document-sharing",
    label: "Document Sharing",
    section: "Navigation",
    keywords: [
      "sharing",
      "share",
      "documents",
      "link",
      "external",
      "access",
      "permission",
      "revoke",
    ],
    href: "/documents/shares",
  },
  {
    id: "nav.mentions",
    label: "Mentions",
    section: "Navigation",
    keywords: ["mentions", "@", "communications", "messages", "notifications", "tagged"],
    href: "/communications/mentions",
  },
  {
    id: "nav.announcement-receipts",
    label: "Announcement Receipts",
    section: "Navigation",
    keywords: [
      "announcements",
      "receipts",
      "read",
      "acknowledge",
      "ack",
      "communications",
      "compliance",
    ],
    href: "/communications/announcements/receipts",
  },
  {
    id: "nav.notification-digest",
    label: "Notification Digest",
    section: "Navigation",
    keywords: ["digest", "notifications", "daily", "summary", "unread", "inbox"],
    href: "/notifications/digest",
  },
  {
    id: "nav.kpi-trends",
    label: "KPI Trends",
    section: "Navigation",
    keywords: ["trends", "kpi", "analytics", "sparkline", "comparison", "period", "metrics"],
    href: "/analytics/trends",
  },
  {
    id: "nav.anomaly-feed",
    label: "Anomaly Feed",
    section: "Navigation",
    keywords: ["anomaly", "anomalies", "alerts", "analytics", "spike", "drop", "unusual", "kpi"],
    href: "/analytics/anomalies",
  },
  {
    id: "nav.company-health",
    label: "Company Health",
    section: "Navigation",
    keywords: ["company health", "composite", "index", "analytics", "score", "executive", "ceo"],
    href: "/analytics/health",
  },
  {
    id: "nav.project-profitability",
    label: "Project Profitability",
    section: "Navigation",
    keywords: [
      "profitability",
      "project",
      "margin",
      "revenue",
      "cost",
      "bi",
      "analytics",
      "portfolio",
    ],
    href: "/analytics/project-profitability",
  },
  {
    id: "nav.employee-roi",
    label: "Employee ROI",
    section: "Navigation",
    keywords: [
      "employee roi",
      "roi",
      "cost per task",
      "productivity",
      "payroll",
      "output",
      "bi",
      "analytics",
    ],
    href: "/analytics/employee-roi",
  },
  {
    id: "nav.inventory-efficiency",
    label: "Inventory Efficiency",
    section: "Navigation",
    keywords: [
      "inventory efficiency",
      "turnover",
      "dead stock",
      "days on hand",
      "stock",
      "procurement",
      "bi",
      "analytics",
    ],
    href: "/analytics/inventory-efficiency",
  },
  {
    id: "nav.safety-analytics",
    label: "Safety Analytics",
    section: "Navigation",
    keywords: [
      "safety analytics",
      "incidents",
      "risk index",
      "injuries",
      "hazard",
      "hse",
      "bi",
      "analytics",
    ],
    href: "/analytics/safety",
  },
  {
    id: "nav.safety-metrics",
    label: "Safety Metrics",
    section: "Navigation",
    keywords: [
      "safety metrics",
      "days since incident",
      "near miss",
      "high risk locations",
      "trir",
      "safety kpi",
      "analytics",
    ],
    href: "/analytics/safety-metrics",
  },
  {
    id: "nav.safety-training",
    label: "Training Compliance",
    section: "Navigation",
    keywords: [
      "training compliance",
      "certification",
      "safety training",
      "expiry",
      "certificates",
      "renewal",
      "analytics",
    ],
    href: "/analytics/safety-training",
  },
  {
    id: "nav.fleet-readiness",
    label: "Fleet Readiness",
    section: "Navigation",
    keywords: [
      "fleet readiness",
      "vehicles",
      "service due",
      "insurance",
      "itp",
      "maintenance",
      "fleet",
      "analytics",
    ],
    href: "/analytics/fleet-readiness",
  },
  {
    id: "nav.tool-inventory",
    label: "Tool Inventory",
    section: "Navigation",
    keywords: [
      "tool inventory",
      "tools",
      "availability",
      "utilization",
      "lost tools",
      "equipment",
      "analytics",
    ],
    href: "/analytics/tool-inventory",
  },
  {
    id: "nav.fleet-utilization",
    label: "Fleet Utilization",
    section: "Navigation",
    keywords: [
      "fleet utilization",
      "mileage",
      "km driven",
      "odometer",
      "vehicle usage",
      "fleet",
      "analytics",
    ],
    href: "/analytics/fleet-utilization",
  },
  {
    id: "nav.attendance-analytics",
    label: "Attendance Analytics",
    section: "Navigation",
    keywords: [
      "attendance analytics",
      "punctuality",
      "absenteeism",
      "workforce",
      "late",
      "presence",
      "bi",
      "analytics",
    ],
    href: "/analytics/attendance",
  },
  {
    id: "nav.demand-forecast",
    label: "Demand Forecast",
    section: "Navigation",
    keywords: [
      "demand forecast",
      "reorder",
      "stockout",
      "replenishment",
      "velocity",
      "procurement",
      "inventory",
      "analytics",
    ],
    href: "/analytics/demand-forecast",
  },
  {
    id: "nav.reports",
    label: "Reports",
    section: "Navigation",
    keywords: ["reports", "export", "csv", "download", "spreadsheet", "excel", "analytics", "data"],
    href: "/analytics/reports",
  },
  {
    id: "nav.command-center",
    label: "Command Center",
    section: "Navigation",
    keywords: [
      "command center",
      "executive cockpit",
      "ceo",
      "overview",
      "cockpit",
      "60 second",
      "dashboard",
      "briefing",
    ],
    href: "/command-center",
  },
  {
    id: "nav.insights",
    label: "Insights",
    section: "Navigation",
    keywords: [
      "insights",
      "command center",
      "recommendations",
      "alerts",
      "rule based",
      "attention",
      "executive",
      "triage",
    ],
    href: "/command-center/insights",
  },
  {
    id: "nav.daily-briefing",
    label: "Daily Briefing",
    section: "Navigation",
    keywords: [
      "daily briefing",
      "morning brief",
      "ceo briefing",
      "executive summary",
      "command center",
      "digest",
    ],
    href: "/command-center/briefing",
  },
  {
    id: "nav.module-status",
    label: "Module Status",
    section: "Navigation",
    keywords: [
      "module status",
      "universal dashboard",
      "operational",
      "modules",
      "health",
      "activity",
      "command center",
    ],
    href: "/command-center/modules",
  },
  {
    id: "nav.recruitment",
    label: "Recruitment",
    section: "Navigation",
    keywords: [
      "recruitment",
      "hiring",
      "candidates",
      "jobs",
      "requisition",
      "pipeline",
      "ats",
      "interview",
    ],
    href: "/recruitment",
  },
  {
    id: "nav.reviews",
    label: "Performance Reviews",
    section: "Navigation",
    keywords: [
      "reviews",
      "appraisal",
      "performance review",
      "cycle",
      "self review",
      "sign-off",
      "goals",
    ],
    href: "/people/reviews",
  },
  {
    id: "nav.schedule",
    label: "Schedule",
    section: "Navigation",
    keywords: ["shifts", "calendar", "rota"],
    href: "/people/schedule",
  },
  {
    id: "nav.operations",
    label: "Operations",
    section: "Navigation",
    keywords: ["stores", "inventory", "tasks"],
    href: "/operations",
  },
  {
    id: "nav.commerce",
    label: "Commerce",
    section: "Navigation",
    keywords: ["shop", "products", "orders", "store", "wishlist", "catalog"],
    href: "/commerce",
  },
  {
    id: "nav.inventory",
    label: "Inventory",
    section: "Navigation",
    keywords: [
      "inventory",
      "stock",
      "stock levels",
      "warehouse",
      "movements",
      "reorder",
      "low stock",
      "stock take",
    ],
    href: "/commerce/inventory",
  },
  {
    id: "nav.promotions",
    label: "Promotions",
    section: "Navigation",
    keywords: ["promotions", "coupons", "discount", "voucher", "promo code", "sale", "offer"],
    href: "/commerce/promotions",
  },
  {
    id: "nav.returns",
    label: "Returns & Refunds",
    section: "Navigation",
    keywords: ["returns", "refund", "rma", "credit", "order return", "refunds"],
    href: "/commerce/returns",
  },
  {
    id: "nav.intelligence",
    label: "Intelligence & Analytics",
    section: "Navigation",
    keywords: ["reports", "ai", "data"],
    href: "/intelligence",
  },
  {
    id: "nav.knowledge",
    label: "Knowledge Base",
    section: "Navigation",
    keywords: ["docs", "wiki", "help"],
    href: "/knowledge",
  },
  {
    id: "nav.crm",
    label: "CRM & Leads",
    section: "Navigation",
    keywords: ["crm", "leads", "pipeline", "sales", "contacts", "deals"],
    href: "/crm",
  },
  {
    id: "nav.crm-analytics",
    label: "Sales Analytics",
    section: "Navigation",
    keywords: ["sales", "analytics", "pipeline", "win rate", "funnel", "forecast", "crm", "reps"],
    href: "/crm/analytics",
  },
  {
    id: "nav.crm-activities",
    label: "CRM Activities",
    section: "Navigation",
    keywords: [
      "activities",
      "calls",
      "meetings",
      "follow-up",
      "tasks",
      "crm",
      "timeline",
      "touchpoints",
    ],
    href: "/crm/activities",
  },
  {
    id: "nav.clients",
    label: "Clients",
    section: "Navigation",
    keywords: ["clients", "customers", "accounts"],
    href: "/clients",
  },
  {
    id: "nav.attendance",
    label: "Attendance",
    section: "Navigation",
    keywords: ["attendance", "clock", "presence", "time", "check-in"],
    href: "/attendance",
  },
  {
    id: "nav.approvals",
    label: "Approvals",
    section: "Navigation",
    keywords: ["approvals", "requests", "sign-off", "authorize"],
    href: "/approvals",
  },
]

const MANAGER_CMDS: CommandEntry[] = [
  {
    id: "people.schedule",
    label: "Manage Schedules",
    section: "People",
    keywords: ["shifts", "rota"],
    href: "/people/schedule",
  },
  {
    id: "people.timeoff",
    label: "Approve Time-Off",
    section: "People",
    badge: "3",
    keywords: ["leave", "vacation"],
    href: "/people/time-off",
  },
  {
    id: "people.org",
    label: "View Org Chart",
    section: "People",
    keywords: ["organization", "hierarchy"],
    href: "/people/org",
  },
  {
    id: "ops.tasks",
    label: "Pending Tasks",
    section: "Operations",
    keywords: ["todo", "queue"],
    href: "/operations/tasks",
  },
  {
    id: "ops.inventory",
    label: "Inventory Check",
    section: "Operations",
    keywords: ["stock", "warehouse"],
    href: "/operations/inventory",
  },
]

const FINANCE_CMDS: CommandEntry[] = [
  {
    id: "finance.forecast",
    label: "Forecast",
    section: "Finance",
    keywords: [
      "forecast",
      "projection",
      "p&l",
      "pnl",
      "break-even",
      "scenario",
      "run rate",
      "cash",
    ],
    href: "/finance/forecast",
  },
  {
    id: "finance.report",
    label: "Monthly Report",
    section: "Finance",
    shortcut: "⌘R",
    keywords: ["revenue", "profit"],
    href: "/finance/reports",
  },
  {
    id: "finance.expenses",
    label: "Approve Expenses",
    section: "Finance",
    badge: "12",
    keywords: ["costs", "reimburse"],
    href: "/finance/expenses",
  },
  {
    id: "finance.invoices",
    label: "Invoices",
    section: "Finance",
    keywords: ["billing", "payment"],
    href: "/finance/invoices",
  },
  {
    id: "finance.payables",
    label: "Accounts Payable",
    section: "Finance",
    keywords: ["payables", "supplier invoices", "bills", "ap", "aging", "outflow", "vendor"],
    href: "/finance/payables",
  },
  {
    id: "finance.payroll",
    label: "Payroll",
    section: "Finance",
    keywords: ["salary", "wages"],
    href: "/finance/payroll",
  },
]

const CEO_CMDS: CommandEntry[] = [
  {
    id: "ceo.kpis",
    label: "View All KPIs",
    section: "CEO Dashboard",
    shortcut: "⌘1",
    keywords: ["metrics", "overview", "revenue"],
    href: "/dashboard",
  },
  {
    id: "ceo.overview",
    label: "Company Overview",
    section: "CEO Dashboard",
    shortcut: "⌘2",
    keywords: ["companies", "entities"],
    href: "/dashboard/overview",
  },
  {
    id: "ceo.group",
    label: "Group Rollup",
    section: "CEO Dashboard",
    keywords: ["companies", "rollup", "consolidated", "holding", "group", "multi-company"],
    href: "/groups",
  },
  {
    id: "ceo.group.manage",
    label: "Manage Group",
    section: "CEO Dashboard",
    keywords: ["group", "companies", "add", "remove", "rename", "members", "administration"],
    href: "/groups/manage",
  },
  {
    id: "ceo.group.create",
    label: "Create Group",
    section: "CEO Dashboard",
    keywords: ["group", "new", "create", "holding", "company group"],
    href: "/groups?new=1",
  },
  {
    id: "ceo.ai",
    label: "AI Briefing",
    section: "CEO Dashboard",
    shortcut: "⌘B",
    keywords: ["intelligence", "summary", "insights"],
    href: "/intelligence/ai",
  },
]

export function getCommandsForRole(role: string): CommandEntry[] {
  const cmds = [...BASE]
  if (MANAGER_ROLES.has(role)) cmds.push(...MANAGER_CMDS)
  if (FINANCE_ROLES.has(role)) cmds.push(...FINANCE_CMDS)
  if (CEO_ROLES.has(role)) cmds.push(...CEO_CMDS)
  return cmds
}
